### ISSUE TITLE
Method params error in ruby 1.9

### ISSUE THREAD

**Issue by schorsch** [brandur/json_schema#43]
i know its an older ruby version but it seems like a quick fix:

the method signature here:
https://github.com/brandur/json_schema/blob/master/lib/json_schema/schema_error.rb#L23

should be changed  from "data: nil" to  "data=nil"

**Comment by brandur** [comment]
I guess it's technically possible to change because that's mostly an internal-only API.

The only thing is that [Ruby 1.9 has been EOL'ed for almost a year now](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/) and we're going to have to say goodbye to it eventually. I'm guessing that getting of Ruby 1.9 is particularly hard for your setup?

**Comment by schorsch** [comment]
I think i can get around 1.9, its just a travis.yml still testing with this ruby version.

**Comment by brandur** [comment]
@schorsch Ah! Good to know. Alright, I'm going to close this issue out for now then, but lemme know if anything else comes up.
